__title__ = 'dppy'
__description__ = 'DPdash data importer'
__url__ = 'https://github.com/harvard-nrg/dppy'
__version__ = '0.1'
__author__ = 'Neuroinformatics Research Group'
__author_email__ = 'info@neuroinfo.org'
